### ISSUE TITLE
Cut new release

### ISSUE THREAD

**Issue by ojongerius** [maasglobal/serverless-plugin-notification#4]
Hi there,

Could you please a new release including https://github.com/maasglobal/serverless-plugin-notification/commit/15ff3b283c37bac0400a18ae127cc1eda9438763 ?

Thanks!

**Comment by ojongerius** [comment]
I started with adding your repo and commit hash via Yarn, then learnt that `serverless` likes to do a `npm ls` which blows up if you don't use `npm`. After some yak shaving I decided it would be easier to publish my own package.

I've pushed a copy of your package to npm: https://www.npmjs.com/package/serverless-plugin-notification-ojongerius and will be more than happy to remove it after you've published 1.3.1 🙇

**Comment by hieuunguyeen** [comment]
I will close this now that we published 1.3.1 :)
